config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  
  get 'welcome/index'
  get '/inicio', to: 'welcome#index'
  
  resources :coins

  root "welcome#index"
  # se quiser definir as rotas específicas para uma operação get
  #get '/coins', to: 'coins#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type#, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :set_locale
    
    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        elsif cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[new edit update create]
  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #cookies[:curso] = "Curso de Ruby on Rails - Jackson Pires [Cookies]"
    #session[:curso] = "Curso de Ruby on Rails - Jackson Pires [Session]"
    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
    def nome_aplicacao
        "CRYPTO WALLET"
    end

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <div class="col-3 bg-light p-3 border">
    <p>
      <strong><%= Coin.human_attribute_name(:description) %></strong>
      <%= coin.description %>
    </p>
    <p>
      <strong><%=Coin.human_attribute_name(:acronym)%></strong>
      <%= coin.acronym %>
    </p>
    <p>
      <strong><%=Coin.human_attribute_name(:url_image)%></strong>
      <%= image_tag coin.url_image, width: 25, height: 25 %>
    </p>
    <p>
      <strong><%=Coin.human_attribute_name(:mining_type)%></strong>
      <%= coin.mining_type.acronym %>
    </p>
  </div>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>
      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form class="row g-3">
    <div class="col-md-3">
      <%= form.label :description, style: "display: block", class: "form-label" %>
      <%= form.text_field :description, class:"form-control" %>
    </div>
    <div class="col-md-3">
      <%= form.label :acronym, style: "display: block" %>
      <%= form.text_field :acronym, class:"form-control" %>
    </div>
    <div class="col-md-3">
      <%= form.label :url_image, style: "display: block" %>
      <%= form.text_field :url_image, class:"form-control" %>
    </div>
    <div class="col-md-3">
      <%= form.label :mining_type_id %>
      <%= form.select("mining_type_id", @mining_type_options, {prompt: 'Selecione...'}, class:"form-select") %>
    </div>
    <br>
    <div class="col-md-3">
      <%= form.submit "#{t('links.confirm')}", class: "btn btn-primary" %>
      <%= link_to "#{t('links.cancel')}", coins_path, class: "btn btn-primary" %>
    </div>
  </form>
<% end %>

app/views/coins/edit.html.erb
falta traduzir titulo
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>
<h3><%= Coin.model_name.human %> <%= link_to t('links.new'), new_coin_path, class: "btn btn-primary btn-sm" %></h3>
<h5><%= cookies[:curso] %></h5>
<h5><%= session[:curso] %></h5>
<div id="coins">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%=Coin.human_attribute_name(:id)%></th>
        <th scope="col"><%=Coin.human_attribute_name(:description)%></th>
        <th scope="col"><%=Coin.human_attribute_name(:acronym)%></th>
        <th scope="col"><%=Coin.human_attribute_name(:url_image)%></th>
        <th scope="col"><%=Coin.human_attribute_name(:mining_type)%></th>
        <th scope="col"><%= "#{t('action')}" %></th>
      </tr>
    </thead>
    <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.id %></td>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, width: 25, height: 25 %></td>
        <td><%= coin.mining_type.acronym %></td>
        <td><%= link_to t('links.show'), coin %></td>
      </tr> 
    <% end %>
    </tbody>
  </table>
</div>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to t('links.destroy'), @coin, method: :delete, data: {confirm: 'Tem certeza?'}, class: "btn btn-primary" %>
  <%= link_to t('links.edit'), edit_coin_path(@coin), class: "btn btn-primary" %> 
  <%= link_to t('links.back'), coins_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
          crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Coins APP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "#{t('home')}", inicio_path, class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to "#{Coin.model_name.human}", coins_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "#{MiningType.model_name.human}", mining_types_path, class:"nav-link"%>
            </li>
          </ul>
          <span class="navbar-text">
          <%# nao funciona o print%>
            <% 
              print "#{t('welcome_text_menu')} #{@meu_nome}" if @meu_nome
              print "#{t('welcome_text_menu')} visitante"
            %>
          </span> 
          <span>
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
              <div class="btn-group mr-2" role="group" aria-label="First group"> 
                <%= link_to image_tag('br_flag.png', width: 25, length: 25), root_path(locale:'pt'), class: "btn btn-light "%>
                <%= link_to image_tag('en_flag.png', width: 25, length: 25), root_path(locale:'en'), class: "btn btn-light" %>
              </div>
            </div>
          <%#alterar para manter na mesma página e nao ficar voltando pro welcome#index%>
          </span>
        </div>
      </div>
    </nav>

    <%= yield %>
    <footer>
      <p><%="#{t('environment')} #{t(Rails.env)}"%></p>
      <p><%= l(Date.today) %></p>
    </footer>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>
      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form class="row g-3">
    <div class="col-md-3">
      <%= form.label :description, style: "display: block", class: "form-label"  %>
      <%= form.text_field :description, class:"form-control" %>
    </div>
    <div class="col-md-3">
      <%= form.label :acronym, style: "display: block", class: "form-label"  %>
      <%= form.text_field :acronym, class:"form-control" %>
    </div>
    <br>
    <div class="col-md-3">
      <%= form.submit "#{t('links.confirm')}" , class: "btn btn-primary" %>
      <%= link_to "#{t('links.cancel')}", mining_types_path, class: "btn btn-primary" %>
    </div>
  </form>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <div class="col-3 bg-light p-3 border">
    <p> 
      <strong><%=MiningType.human_attribute_name(:description)%></strong>
      <%= mining_type.description %>
    </p>
    <p>
      <strong><%=MiningType.human_attribute_name(:acronym)%></strong>
      <%= mining_type.acronym %>
    </p>
  </div>
</div>

app/views/mining_types/edit.html.erb
falta traduzir titulo
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>
<h3><%= MiningType.model_name.human%> <%= link_to t('links.new'), new_mining_type_path, class: "btn btn-primary btn-sm" %> </h3>
<div id="mining_types">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%=MiningType.human_attribute_name(:id)%></th>
        <th scope="col"><%=MiningType.human_attribute_name(:description)%></th>
        <th scope="col"><%=MiningType.human_attribute_name(:acronym)%></th>
        <th scope="col"><%= "#{t('action')}" %></th>
      </tr>
    </thead>
    <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.id %></td>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>
<br>
<div>
  <%= link_to t('links.destroy'), @mining_type, method: :delete, class: "btn btn-primary"  %>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class: "btn btn-primary"  %>
  <%= link_to t('links.back'), mining_types_path, class: "btn btn-primary"  %>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid bg-light text-dark p-5">
    <div class="container bg-li p-5">
        <h1 class="display-4"><%=t('welcome')%></h1>
        <hr>
        <p><%= t('welcome_text') %></p>
        <%= link_to "#{Coin.model_name.human}", coins_path, class:"btn btn-primary" %>
    </div>
</div>
<p><%=" #{t('idiom_text')} #{t('actual_locale')}" %></p>
</div>